package hue.captains.singapura.js.homing.relgrid.protocol;

import hue.captains.singapura.js.homing.codec.ObjectDefinition;
import hue.captains.singapura.js.homing.ssjs.test.JsModuleTestBase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.lang.reflect.RecordComponent;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * RFC 0050 · Episode 2, ext5 — the generated protocol, proved where it matters.
 *
 * <p>The load-bearing test is {@link #everyClassHasExactlyItsRecordsFields()}:
 * it is driven by reflection over the manifest, so it covers a kind added
 * tomorrow without being edited. That is the whole point of generating — drift
 * between the Java record and the JS class fails the build the day it appears,
 * rather than being caught by a test somebody remembered to write.</p>
 */
class RelGridProtocolGenTest extends JsModuleTestBase {

    @BeforeEach
    void setup() {
        js = buildContext();
        js.eval("js", RelGridProtocolGen.generate());
    }

    private boolean evalBool(String expr) { return js.eval("js", expr).asBoolean(); }

    @Test
    void theGeneratedModuleEvaluatesAtAll() {
        // Evaluating it in setup is the assertion: a manifest in the wrong order
        // emits a forward reference and throws here rather than in a browser.
        assertTrue(evalBool("typeof RelGridRange === 'function' && typeof RelGridSelectionChanged === 'function'"),
                "the generated module declares every class the manifest names");
    }

    @Test
    void everyClassHasExactlyItsRecordsFields() {
        var mismatches = new ArrayList<String>();
        for (ObjectDefinition<?> def : RelGridProtocolManifest.ENTRIES) {
            Class<?> type = def.type();
            var expected = new ArrayList<String>();
            for (RecordComponent c : type.getRecordComponents()) expected.add(c.getName());

            // Construct it in JS with one argument per component, then read back
            // the field names the constructor actually assigned.
            var args = new ArrayList<String>();
            for (RecordComponent c : type.getRecordComponents())
                args.add(c.getType().isArray() || java.util.Collection.class.isAssignableFrom(c.getType()) ? "[]" : "0");
            String actual = js.eval("js",
                    "Object.keys(new " + type.getSimpleName() + "(" + String.join(", ", args) + ")).join(',')").asString();

            if (!String.join(",", expected).equals(actual))
                mismatches.add(type.getSimpleName() + ": java " + expected + " vs js [" + actual + "]");
        }
        assertEquals(List.of(), mismatches,
                "a generated class must carry exactly its record's components, in order");
    }

    @Test
    void aValueObjectIsFrozenAllTheWayDown() {
        assertTrue(evalBool("""
                (() => {
                    var r = new RelGridRange(1, 2, 3, 4);
                    if (!Object.isFrozen(r)) return false;
                    try { r.i0 = 99; } catch (e) { /* strict mode throws; sloppy silently ignores */ }
                    if (r.i0 !== 1) return false;

                    var mine = [r];
                    var s = new RelGridSelectionChanged(mine);
                    if (!Object.isFrozen(s) || !Object.isFrozen(s.ranges)) return false;
                    // The caller's own array is COPIED before it is frozen, so handing one
                    // over does not freeze it under the caller's feet.
                    if (Object.isFrozen(mine)) return false;
                    mine.push(r);
                    return s.ranges.length === 1 && s.ranges[0].i1 === 3;
                })()"""), "instances and their collections are frozen, and a caller's array is copied first");
    }

    @Test
    void anAbsentCollectionBecomesAnEmptyOne() {
        assertTrue(evalBool("""
                (() => {
                    var s = new RelGridSelectionChanged();
                    return Array.isArray(s.ranges) && s.ranges.length === 0 && Object.isFrozen(s.ranges);
                })()"""), "a missing collection is an empty frozen one, never undefined");
    }

    @Test
    void theGeneratedBodyCarriesItsProvenanceAndNoBehaviour() {
        String body = RelGridProtocolGen.generate();
        assertTrue(body.contains("GENERATED by RelGridProtocolGen"), "the body says where it came from");
        assertTrue(body.contains("hue.captains.singapura.js.homing.relgrid.protocol.RelGridRange"),
                "each class names the Java record it was generated from");
        // Data only: no DOM, no grid, and no method beyond the constructor.
        for (String forbidden : List.of("document", "window", "addEventListener", "RelGrid(", "function ")) {
            assertTrue(!body.contains(forbidden), "the protocol is data only, but it contains: " + forbidden);
        }
    }
}
