package hue.captains.singapura.js.homing.relgrid.protocol;

import hue.captains.singapura.js.homing.codec.ObjectDefinition;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Build-time entry point: walk {@link RelGridProtocolManifest} and emit one ES
 * module holding every protocol class.
 *
 * <p>Run by the Maven exec plugin at {@code process-classes}, writing into
 * {@code target/classes} — never into {@code src/main/resources}, which is the
 * Generated and Hand-Written Live Apart doctrine and is checked by a test. The
 * filename must equal {@link RelGridProtocolModule}'s simple name, because that
 * is how the framework finds a module body on the classpath.</p>
 *
 * <p>{@link #generate()} is the pure form, so the same traversal can be
 * asserted in a test without touching a filesystem.</p>
 */
public final class RelGridProtocolGen {

    private RelGridProtocolGen() {}

    /** Must match RelGridProtocolModule's simple name. */
    static final String FILE_NAME = "RelGridProtocolModule.js";

    public static void main(String[] args) throws IOException {
        if (args.length != 1) throw new IllegalArgumentException("Usage: RelGridProtocolGen <output-directory>");
        Path outDir = Paths.get(args[0]);
        Files.createDirectories(outDir);
        String body = generate();
        Path out = outDir.resolve(FILE_NAME);
        Files.writeString(out, body, StandardCharsets.UTF_8);
        System.out.println("[RelGridProtocolGen] wrote " + out + " (" + body.length() + " chars, "
                + RelGridProtocolManifest.ENTRIES.size() + " types)");
    }

    public static String generate() {
        var sb = new StringBuilder();
        sb.append("// =============================================================================\n");
        sb.append("// GENERATED by RelGridProtocolGen — do not edit by hand.\n");
        sb.append("// Source of truth: RelGridProtocolManifest, and the Java records it names.\n");
        sb.append("//\n");
        sb.append("// The ask protocol: what the grid asks and what it accepts back. Every class\n");
        sb.append("// here is a value object — deeply frozen, no behaviour — and this module is\n");
        sb.append("// DATA ONLY: no DOM, no grid. Domain code may depend on it to answer without\n");
        sb.append("// depending on the grid.\n");
        sb.append("// =============================================================================\n");
        for (ObjectDefinition<?> def : RelGridProtocolManifest.ENTRIES) {
            sb.append('\n');
            sb.append(FrozenClassCodeGen.INSTANCE.generate(def));
        }
        return sb.toString();
    }
}
